# Generated by Django 4.2.5 on 2023-09-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='pass', max_length=10),
            preserve_default=False,
        ),
    ]
