# Generated by Django 4.2.5 on 2023-11-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0005_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=50)),
                ('pettype', models.CharField(max_length=50)),
                ('petbreed', models.CharField(max_length=50)),
                ('petage', models.CharField(max_length=50)),
                ('petservice', models.CharField(max_length=50)),
                ('petgender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_charge', models.IntegerField()),
                ('image', models.ImageField(upload_to='services/')),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
