# Generated by Django 4.2.5 on 2023-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_bookingcart_cartitem_service_delete_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
    ]
