# Generated by Django 4.2.5 on 2023-11-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcart',
            name='bookingdate',
            field=models.CharField(default='value', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingcart',
            name='bookingtime',
            field=models.CharField(default='value', max_length=5),
            preserve_default=False,
        ),
    ]
