# Generated by Django 4.2.5 on 2023-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_bookingcart_bookingdate_bookingcart_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
