# Generated by Django 4.2.5 on 2023-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_userdetails_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
