# Generated by Django 4.2.5 on 2023-12-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
