# Generated by Django 4.2.5 on 2024-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_bookingcart_email_bookingcart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_name', models.CharField(max_length=255)),
                ('boarding_charge', models.IntegerField()),
                ('image', models.ImageField(upload_to='boarding/')),
                ('boarding_description', models.TextField()),
            ],
        ),
    ]
