# Generated by Django 4.2.5 on 2024-02-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_boarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarding',
            old_name='boarding_name',
            new_name='boarding_type',
        ),
    ]
