# Generated by Django 4.2.5 on 2024-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_rename_boarding_name_boarding_boarding_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('pickup_date', models.CharField(max_length=50)),
                ('drop_date', models.CharField(max_length=50)),
                ('appointment_time', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
    ]
