# Generated by Django 4.2.5 on 2024-02-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_petboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petboarding',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='petboarding',
            name='drop_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='petboarding',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
