# Generated by Django 4.2.5 on 2024-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_alter_petboarding_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petboarding',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
