# Generated by Django 4.2.5 on 2024-02-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_alter_petboarding_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petboarding',
            name='street',
        ),
    ]
