# Generated by Django 4.2.5 on 2024-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_remove_petboarding_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='petboarding',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
