# Generated by Django 4.2.5 on 2024-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_petboarding_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(max_length=255)),
                ('vaccination_charge', models.IntegerField()),
                ('image', models.ImageField(upload_to='vaccination/')),
                ('vaccination_description', models.TextField()),
            ],
        ),
    ]
