# Generated by Django 4.2.5 on 2024-03-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_alter_vaccination_vaccination_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarding',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
