# Generated by Django 4.2.5 on 2024-03-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_boarding_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('vaccination_name', models.CharField(max_length=100)),
                ('previous_vaccination_date', models.DateField()),
                ('previous_vaccination_name', models.CharField(max_length=100)),
                ('next_vaccination_date', models.DateField()),
                ('vet_name', models.CharField(max_length=100)),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
