# Generated by Django 4.2.5 on 2024-04-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_petvaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_type', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
