# Generated by Django 4.2.5 on 2024-04-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
