# Generated by Django 4.2.5 on 2024-04-07 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_leaveapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
